### ISSUE TITLE
[Enhancement] Build options for ignoring files

### ISSUE THREAD

**Issue by cgriffin4** [Polymer/polymer-cli#180]
The ability to set ignore paths is crucial to having a useful build tool. Maintaining the syntax implemented in vulcanize may assist in developer migration to the new toolset as well.

Ignoring unchanged files is less serious but would allow for server/cdn caching mechanisms while deploying.

**Comment by justinfagnani** [comment]
Can you describe the behavior you want a little more? Do you want the files copied unchanged, or ignored completely?

**Comment by cgriffin4** [comment]
Giving this a second look I'd like to see this merged with issue #32 as it is the enhancements are standard with deployment tools rather than build tools.

'Ignore Paths' option: specifically so that I can output only the files needed in the site. Ignoring /test/ or /demo/ in every component.

'Changed' option: so that I'm not outputting a brand new /images/ directory for every change to the website. Compared to choosing a 'Clean' option which would start by deleting existing files.

**Comment by abdonrd** [comment]
👍 about this.

At the root we need to avoid `bower.json`, `polymer.json`, `README.md`, `/test/`, etc

**Comment by Eugenitals** [comment]
+1

**Comment by justinfagnani** [comment]
We're working on a few things in this area. First the build pipeline code is being put in a separate library called polymer-build, so that it can be pulled into a gulpfile and customized. As part of that library, we're reworking how files are consumed  into the pipeline. A project's own sources will continued to be pushed into the pipeline by default: entrypoint, shell, fragments and src/**. This will make it easy to compile or optimize files, and refer to them by their final name. An ignore list will be added to clean up the final output. What we've been calling the "dependencies" - really the third-party dependencies will only be pull in on request. Anything that Hydrolysis needs to visit because of an HTML import or script tag will be pulled into the pipeline and processed by the steps added to the dependencies stream (we're looking for a new name for this stream, btw).

First reports from @FredKSchott on a prototype of this technique brings our build output for a demo from 13MB to 650k. It doesn't change what's delivered to the client in anyway, but for those worried about the size of their deployment, this will help a lot. More importantly, it'll speed up builds drastically by not even processing most files in bower_components/.

We'll keep you posted!

**Comment by FredKSchott** [comment]
Aaaaaaaand this has been released in v0.13.0! 

Closing this issue now, but we'd love to hear how the newest version is working for you. Please update to the latest version and try it out! If you find a bug, please create a new issue.

For anyone looking for more control over your builds, check out the [polymer-build](https://github.com/Polymer/polymer-build) standalone library that the CLI is now using internally.

**Comment by Eugenitals** [comment]
It is awesome! 
After updating to polymer-cli#0.13, i was able to delete my grunt.src(...) ignore list:
`var ignore = [
    'gulp', 'gulp/**',
    'test', 'test/**',
    'target', 'target/**',
    'server', 'server/**',
    'bower.json',
    'package.json',
    'version.json',
    'pom.xml',
    'settings.xml',
    'nginx.conf',
    'README.md',
    '*.iml'
]`
