### ISSUE TITLE
Build time for complete apps?

### ISSUE THREAD

**Issue by LostInBrittany** [Polymer/polymer-cli#254]
I've used polymer-cli to create a PWA version of a dashboard app that I'd built with Polymer (using pages.js as router...). I've begun from scratch, and imported only the components needed for the new app, using the app- elements when possible (router, par exemple).

Everything is great, except the building phase, that takes more than 5 minutes ! 

In the old app I used vulcanize as build tool, it wasn't quick but it was way faster than that, more or less one minute.

Is such a slow build time normal?

**Comment by justinfagnani** [comment]
It's a little slow right now, but we haven't seen 5 minutes, usually on the order of a few seconds.

We know that we run the analyzer and vulcanize multiple times during the bundling phase. This should scale with the number of fragments. Hw many fragments do you have? Do you see the same long times with just an entrypoint?

**Comment by CTOJoe** [comment]
We also have tried switching from vulcanize to polymer cli and are experiencing build times of over 5 minutes. This is also on pretty performant machines. Could build time essentially be cut in half if there was a flag to compile just bundled or unbundled?

**Comment by justinfagnani** [comment]
Even half the time at 2.5 minutes is far too long. I'd like to figure out what it is about the project or environment that's causing such long builds. Could we see some package.json dependency sections and maybe we can reproduce ourselves?

**Comment by LostInBrittany** [comment]
That works be great, right now I have no use for the unbundled, I'd really
like the flag 😊

**Comment by LostInBrittany** [comment]
I can send you a bower.json and a package.json tomorrow, if it can help.

**Comment by vaadin-marcus** [comment]
I have an app that was initially built with PSK that I'm now migrating to use Polymer CLI. 

With the PSK `gulp` build target, a full build too 18s, of which 16s was vulcanize. With `polymer build` the bundled build takes 2.5minutes+ (it crashes at that point). 

It seems like it's trying to uglify and include everything in the `bower_components` folder, including demos, which certainly brings up the build time. 

On a related note: if I include polymerelements/paper-elements and iron-elements instead of the individual elements, does it increase the build time or bundle size? I know that with PSK and vulcanize, it would only include the actual components that had been imported in the bundle.

**Comment by LostInBrittany** [comment]
I've just updated to `polymer-cli` v. 0.11.1 and the same build that took 5 minutes takes instead 2 minutes. And that's *great* !!!

**Comment by FredKSchott** [comment]
Closed by #310
