### ISSUE TITLE
`polymer build` includes extraneous files in output

### ISSUE THREAD

**Issue by tony19** [Polymer/polymer-cli#265]
### Description
The `polymer build` command includes extraneous files (i.e., `test/*`, `README.md`, `bower.json`, `polymer.json`) in the `build/bundled` and `build/unbundled` output directories.

### Versions & Environment
- Polymer CLI: 0.11.0
- node: 6.2.1
- Operating System: OS X El Capitan

#### Steps to Reproduce
 1. Run `polymer init app-drawer-template` in a new directory.
 2. Run `polymer build`

#### Expected Results
The directories under `build/` contain only files necessary to run the app.

#### Actual Results
Unnecessary files (starred) are included:

    ├── README.md*
    ├── bower.json*
    ├── bower_components*
    │   ├── ...
    ├── images
    │   ├── app-icon-144.png
    │   ├── app-icon-32.png
    │   └── app-icon.svg
    ├── index.html
    ├── manifest.json
    ├── polymer.json*
    ├── service-worker.js
    ├── src
    │   ├── my-app.html
    │   ├── my-icons.html
    │   ├── my-view1.html
    │   ├── my-view2.html
    │   └── my-view3.html
    ├── sw-precache-config.js
    └── test*
        ├── index.html*
        └── my-view1.html*

**Comment by cdata** [comment]
I would like to propose that this be the standing feature issue for implementing ignore lists for files.

**Comment by mbleigh** [comment]
I would like to propose that the cli-generated app template use a `public` or `app` directory instead of putting application files at the same level as `README.md` etc. As much as I love the idea of the simplicity of the Polymer CLI, I can't really use it the way I want as-is.

**Comment by abdonrd** [comment]
@mbleigh I agree to have a `public`/`app` directory. :)

**Comment by jimbojetlag** [comment]
Please, could the developers of the current deploy design explain why is it this way? Why would I want to publish my tests, internal README, together with all bower package dependencies and their tests and demos to the whole world?

Would it be possible increase the priority of this issue to high? The outcome of the build command is barely deployable.

**Comment by FredKSchott** [comment]
Thanks for the feedback everyone. Given how important this is appears to be, I'm going to bump up the priority on this and start working on a fix.

To give a peak into how build currently works, it currently reads all source files & all bower dependency files via two separate streams. Different logic is applied to the files passing through each stream, and then finally they are merged back together into the `build/bundled` & `build/unbundled` directories. Currently we copy over all dependencies via `bower_components/**/*` & all source files via `/**/*` (excluding the `bower_components` & `node_modules` directories). This was written to be an intentionally loose default behavior, given that developers sometimes need to serve additional files from their app.

If you are having trouble with extraneous files from your own project (`README.md`, `bower.json`, etc.) ending up in your build directory, this is something that can be fixed by adding support for custom source file include/ignore rules. 

If you are having trouble with the actual size of each build directory, this is entirely due to all the unnecessary files pulled in via the `bower_components/` directory (`10.9 MB` of `11.3 MB` for app-template-layout). This is a much more difficult problem to solve, since dependencies don't list which of their files are extraneous and which are essential. I'd love to see how other build processes solve this problem. As far as I know, the full `bower_components/` directory is always used.

**Comment by FredKSchott** [comment]
I'm digging into different solutions for this now, but as of this moment I agree with @cdata that adding support for explicit, custom source file add/ignore rules is the way to go.

**Comment by jimbojetlag** [comment]
To me serving `bower_components/` to the public seems odd. It feels like I'm putting the internals of my projects in public. Things like `bower_components/` are the raw ingredients, they should be used to bake the final product which gets served to public. Serving them directly is not the right way to go.

This is a 'solved' problem, we do not need to re-invent the wheel of how to bundle frontend assets for web apps. This has been addressed years ago, and it works well for others, why not following them?

Polymer is by Google, what does Google do when deploying Gmail?

**Comment by FredKSchott** [comment]
@jimbojetlag It sounds like your frustrations are with Bower and its requirements around how the  `bower_components/` directory is served. That is a much larger discussion that is outside the scope of this issue. 

Please see https://github.com/Polymer/polymer/issues/2578 and its child-issues if you would like to add your voice to the discussion.

**Comment by jimbojetlag** [comment]
@FredKSchott sorry if that was unclear. I'm not against bower, I think it's the proper choice over npm.

I was referring to the bower components directory, or any other source code structure for that matter, that gets directly from development to production. There should be a solution to _bundle_ the development source code to production deployable, not _copying_.

**Comment by FredKSchott** [comment]
Closed by #310
