### ISSUE TITLE
Use a different port if the current one is in use when serving

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer-cli#301]
Use case:

>  the user is serving more than one project at the same time.

It would be neat to find a port number that is open when I call `polymer serve` if I don't explicitly specifying the port number. Similar to how browser-sync does it.

Finally, copy that URL to the clipboard.

**Comment by FredKSchott** [comment]
Love the idea, do you have any idea what additional code/libraries are needed to make this work? Our dependency graph is already too big, so if this logic requires any complex additional dependencies it might not be worth the tradeoff.

**Comment by bernardius** [comment]
Hey @FredKSchott,

I want to fix this but I have a question about the context. Since the Express server is created in Polyserve, does an issue need to be created in that repo? Or should I just create PR there and reference it here? I am new to contributing to open source stuff so any advice is appreciated.

**Comment by FredKSchott** [comment]
Thanks @bernardius! No problem, having multiple dependencies and repos can make open-source coordination difficult.

The current plan we'd like to pursue is outlined here: https://github.com/Polymer/polymer-cli/issues/300#issuecomment-236659044 Unfortunately no one has had time to look at it since then, so it would be great if you'd be able to. Feel free to reference this issue in the polyserve PR.

**Comment by TimvdLippe** [comment]
I think this issue was fixed with the find-port package in polyserve?

**Comment by FredKSchott** [comment]
Yes! Fixed on master and will be pushed out soon.
