### ISSUE TITLE
[bug] manifest.json not includes in build

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer-cli#344]
### Description
`manifest.json` not includes in build

### Versions & Environment

- Polymer CLI: 0.13.0
- node: 6.3.1
- Operating System: OS X 10.11.6

#### Steps to Reproduce
polymer init (app-drawer-template)
polymer build

#### Expected Results
Build folder contain `manifest.json` file

#### Actual Results
There is no `manifest.json` file in build/*

**Comment by AliMD** [comment]
same issue as node 4.4.7

**Comment by AliMD** [comment]
temporary solution: move manifest.json to `src` and update `index.html` link href

**Comment by RoXuS** [comment]
@AliMD you can use the following command : `polymer build --include-dependencies="?(styles.css|manifest.json|...)"`

**Comment by FredKSchott** [comment]
@RoXuS is correct, you can include additional dependencies via that argument. You could also define your manifest.json as an additional source file as well (see `polymer help build` for a list of all valid arguments). As of right now there's no real difference between the two but it's probably best to include it as a source file instead of as a dependency.
