### ISSUE TITLE
PolymerFire Application Template

### ISSUE THREAD

**Issue by phidias51** [Polymer/polymer-cli#456]
It would be really helpful if there was a PolymerFire version of the shop application template.  Currently there have been a number of issues wrt getting PolymerFire to run, and having a working example that we can use as a starting point would make this much easier.

**Comment by oneezy** [comment]
To bring the discussion back up for `generator-polymer-init` custom build templates,

For me, 
there still seems to be a little* confusion on how the inner workings come together (or should I say, _are coming together_). It looks like the guys have been doing some work for the [0.18.0-alpha.2](https://github.com/Polymer/polymer-cli/commit/2eac5c979f6eafbb655f1abe874820a3243eeafb) in bringing the **New Analyzer** into the CLI, which could bring w/ it _potentially breaking changes_.

Along w/ this, my last attempt in creating a `generator-polymer-init` template, I ran into some **Global** and **Local** Gulp 4.0 compatibility issues..and things got a little weird (for lack of better words). I wasn't able to spend to much time flushing these issues out, though, I'm here writing this post because I've found some time haha :) 

-----

@FredKSchott , would you say it's safe to mess around in this area or should we hold off until you guys get the new Analyzer wrapped up?

**Comment by FredKSchott** [comment]
There are a few things here, I'll try to respond to them all:

- As far as i know, there are no current plans for the polymer team to build and maintain a polymerfire shop template.
- I would ask about polymerfire resources/examples/demos in our Slack channel, I'm sure our community will be able to help you get started. @oneezy included a helpful video above to get you started.
- Polymer CLI is still under active development, so do expect things to change and new features to be added on a regular basis. However we know that a lot of people are already relying on the CLI today, so we will always do our best to keep breaking changes to a minimum.
- The Changelog will always highlight new features and changes.
- Contributions are always welcome. If something about our tooling doesn't work or you wish it did something better, please file an issue so that we can discuss. Filing an issue to discuss a new feature / behavior change before creating the PR is almost always a good idea.
- A few recent issues have highlighted the fact that we should have a more open roadmap for the CLI. This is something we'll focus on as we move to v1.0.

**Comment by FredKSchott** [comment]
Closing this issue because there's nothing actionable here in regards to the CLI, but feel free to continue the discussion here (or better yet, in our #tools channel on slack :).

**Comment by phidias51** [comment]
@FredKSchott Regarding your comment about "no current plans for the polymer team to build and maintain a polymerfire shop template"

I suspect as Polymer continues to grow, more of the Google API will be exposed via web components. This will no doubt require collaboration between product teams in order to make it a reality.  In this particular instance, some collaboration between the CLI team the polymerfire team, would go a long way to insure that Polymer+Firebase becomes the default way that developers build new web applications.
