### ISSUE TITLE
Travis runs test suite 3 times

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer-cli#520]
The current Travis setup runs the test suite 3 times. By default Travis runs `npm install`, then in the [`before_script`](https://github.com/Polymer/polymer-cli/blob/master/.travis.yml#L7) `npm install` is run again and lastly the script itself does `npm test`.

Since `npm install` triggers the `prepublish` event, `npm` will run `npm test` per https://github.com/Polymer/polymer-cli/blob/master/package.json#L16 Therefore for both installs and the normal script, the test suite is triggered.

An example job is https://travis-ci.org/Polymer/polymer-cli/jobs/184777722 Is this intended behavior? I would expect the Travis test suite to be run only once.

**Comment by FredKSchott** [comment]
Not intentional, just npm weirdness :) We're experimenting with `np` as a better publishing tool, if we decide to move to that we could remove the `prepublish` step, which would fix tests running after install.

But npm install running twice is strange no matter what, that should definitely not happen. @TimvdLippe interested in removing `npm install` from before_script?
