### ISSUE TITLE
insertPrefetchLinks adds faulty imports that cause 404's

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/polymer-cli#600]
### Description
Using the `insertPrefetchLinks` build option adds incorrect link imports to the app shell and fragments which generate wasted 404 requests.

### Versions & Environment
- Polymer CLI: 0.18.0-pre.13
- node: v6.2.1
- Operating System: macOS Sierra 10.12.3

#### Steps to Reproduce
1. Create an application project: `polymer init application`
2. Build: `polymer build --insert-prefetch-links `

#### Expected Results
link prefetch entries with correct URLs are added to index.html, app shell and fragments (or just to index.html ?)

#### Actual Results
The app shell and fragments contain duplicate imports with versions that lack either the root-relative path or the relative path of the original imports.

i.e. my-app.html will contain _both_
```html
<link rel="import" href="../bower_components/polymer/polymer-element.html">
```
and
```html
<link rel="import" href="bower_components/polymer/polymer-element.html">
```
(note lack of path prefix)

Ideally all paths would be relative to the root (or any base href set in index.html?)

**Comment by FredKSchott** [comment]
I can't reproduce following your steps, could you install the latest CLI version (`npm i -g polymer-cli@next`) and revise your steps so that I can see what you're seeing on my machine? For example, when I run `polymer build --insert-prefetch-links` all prefetch imports are added added to index.html, not `my-app.html`.

**Comment by CaptainCodeman** [comment]
I'm already using the current latest @next version. The prefetch links _are_ added to `index.html` but the other elements then also contain duplicate imports with the wrong path that causes 404's

**Comment by jifalops** [comment]
I'm having the same issue with `Polymer CLI: 0.18.0-pre.13` (on Linux Mint). Changing [insertPrefetchLinks](https://github.com/jifalops/app-starter/blob/dev/polymer.json#L31) to false will build and run without error. If it is true, `polymer serve`ing the build results in many 404s because it is looking for `src/bower_components` instead of the correct `bower_components`.
![image](https://cloud.githubusercontent.com/assets/826613/24119621/42cfc838-0d88-11e7-9242-9fb66cd1bd06.png)

**Comment by FredKSchott** [comment]
Okay, I still can't reproduce with either `application` template but I can reproduce with `polymer-starter-kit`. Taking a look at this now...

**Comment by FredKSchott** [comment]
So for this feature, it looks like the CLI is relying on some old, flakey methods of url -> path transformation. Once we pull this out of the CLI and into the lower-level polymer-build library (currently in progress) we should have the new, more stable url -> path transformations that were built in the polymer-build library.

I'll update this issue on progress.

**Comment by lawrencemok** [comment]
I can confirm this.

This happen only when polymer.json uses any of these entries:

fragments
shell

Also it seems when not using fragments/shell entries, prefetch <link> tags were added to index.html and works correctly. But when shell entries is used, the prefetch <link>s were added to the shell file output (e.g. src/my-app.html) which
