### ISSUE TITLE
Polymer build - insert prefetch links option should have an option to add async to the generated <link> tags

### ISSUE THREAD

**Issue by lawrencemok** [Polymer/polymer-cli#637]
Just a suggestion, polymer build - insert prefetch links option should have an option to add async to the generated <link> tags

Sites built with Polymer usually need an initial load of 100KB+ (depending how much web components used) before the browser start rendering anything, which takes over 2 seconds of delay making the site appears slow in response.

Perhaps with async added, the initial response will looks faster?

**Comment by FredKSchott** [comment]
That's a great question. `--insert-prefetch-links` actually does do some smart optimizations already where it can. In the shell/entrypoint, each added link is of `rel="prefetch"` to be loaded without blocking.

For each application fragment, the prefetch links are `rel="import"` because a fragment would need all dependencies loaded before it could run. But having them all included lets the browser start loading all multiple dependencies at once (without it, the browser would need to parse each import before fetching its dependencies).

So my understanding is that async would break because of ordering problems. But if someone is interested in creating a benchmark I'd love to reopen this and take a look.
