### ISSUE TITLE
Polymer Install shorthand like NPM and Bower

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-cli#687]
It would be fantastic if the polymer cli could support the a shorthand of `polymer i` for `polymer install`.

**Comment by FredKSchott** [comment]
+1, this would be nice to have!

If you (or anyone else) is interested in implementing I'd be available to review

**Comment by stramel** [comment]
@FredKSchott I wouldn't mind adding it but I wasn't sure if there was something to already handle aliases or not. Was thinking about accepting a name in the constructor that would be able to provide a command name? Definitely open to any direction you can give.

**Comment by FredKSchott** [comment]
I would add an `alias: string[]` property to each command, and then have `polymer-cli.ts` add commands by both name and alias. 

Finer points:
- The help command should automatically list aliases in the help output for any one command (not necessary for the general `$ polymer help` output).
- `polymer-cli.ts` should error if there's a duplicate name/alias conflict, so that if we ever mess up the tests won't pass.

**Comment by stramel** [comment]
Done with #721
