### ISSUE TITLE
`polymer serve` on Build an element tutorial repo gives the wrong URL

### ISSUE THREAD

**Issue by wmginsberg** [Polymer/polymer-cli#705]
### Description
While doing the Build an element tutorial, I ran polymer serve and noticed that the URL suggested from the CLI was leading to a Not Found page. The URL sent out was http://127.0.0.1:8081/components/icon-toggle/  so I tried http://127.0.0.1:8081/components/icon-toggle/demo and it worked. Unsure if this is a CLI issue or a github repo/starter code issue. 

### Versions & Environment
- Polymer CLI: 0.18.1
- node: v6.4.0
- Operating System: macOS Sierra 10.12.4

#### Expected Results
I can see the demo code from the returned URL 

#### Actual Results
I receive a Not Found error page when trying to see demo code

**Comment by wmginsberg** [comment]
There is a note in the tutorial later on but it's farther down and I didn't see it til I kept going 

"If this text doesn’t appear, make sure you’re looking at the the demo folder itself, or at demo/index.html, not at toggle-icon.html or toggle-icon-demo.html."

**Comment by justinfagnani** [comment]
I think this should be a docs issue. We point to the root of the component folder, and yes, there's no guarantee that there's something loadable there.

**Comment by arthurevans** [comment]
Hm. We could add an index or something that just redirects to the /demo/ directory, but I think that would be confusing since it's not a standard part of an element project.

Aha! How about if we add an `index.html` that mentions the name of the project, and tells people that they if they're doing the tutorial they probably want to be looking at the demo directory?

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#2080
