### ISSUE TITLE
Lazy imports not handled properly when generating push manifests

### ISSUE THREAD

**Issue by graynorton** [Polymer/polymer-cli#749]
### Description

Unless I'm misunderstanding how they're supposed to work, it seems that lazy imports are not being handled properly when generating push manifests.

I would expect a lazy import...

* ...to be included on the top level of the push manifest (with its dependencies listed below it, if the build is unbundled)
* ...*not* to be included in the manifest as a dependency to be pushed with the document that lazily imported it

In fact, neither of the above is true – a lazy import *is not* included as a fragment on the top level of the push manifest and *is* listed as a resource to be pushed with the document that imported it.

### Versions & Environment

- Polymer CLI: 1.0.0
- node: 6.3.0
- Operating System: macOS Sierra

#### Steps to Reproduce

1. `polymer init polymer-2-starter-kit`
2. Delete the `fragments` entry from `polymer.json`, since lazy imports should be implicitly recognized as fragments (the fact that the fragments are explicitly specified seems to be a [separate bug](https://github.com/Polymer/polymer-cli/issues/748) in the template)
3. `polymer build --preset=es6-unbundled --add-push-manifest`, or `polymer build --preset=es6-bundled --add-push-manifest`

#### Expected Results

Generated push manifest *does not* include the various `src/my-viewX.html` files as resources to be pushed for the `src/my-app.html` fragment.

Generated push manifest *does* include top-level entries for the `src/my-viewX.html` files

#### Actual Results

Generated push manifest *does* include the various `src/my-viewX.html` files as resources to be pushed for the `src/my-app.html` fragment.

Generated push manifest *does not* include top-level entries for the `src/my-viewX.html` files

**Comment by usergenic** [comment]
With the merge of https://github.com/Polymer/polymer-build/issues/246 the remaining issue is that lazy-imports are not automatically recognized to be fragments for the purpose of the push-manifest.json.

Bundler recognizes lazy-imports as fragments, because that is a requirement of how bundler much treat them when apportioning files to various bundles.  In the case of polymer-build, which is where the push-manifest logic lives, there is no such analysis. 

Created https://github.com/Polymer/polymer-build/issues/247 to track lazy imports automatically being recognized as fragments by build.
