### ISSUE TITLE
Test and validate arbitrary combinations of flags

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer-cli#92]
- [x] one endpoint
- [x] one endpoint + shell
- [x] one endpoint + fragments
- [x] one endpoint + shell + fragments

**Comment by justinfagnani** [comment]
The valid combinations I see:

  1. Just main. No laziness, no path-based routing, everything bundled into one file
  2. Main + shell: For path-based routing. main is not bundled, shell it. main is small because it will be served from many URLs
  3. Main + shell + entrypoints: all the laziness and bundling
  4. Just entrypoints? Bundled, multi-page app?
